name:                string-transform
version:             0.0.1
synopsis:            simple and easy haskell string transform wrapper
github:              ncaq/string-transform
license:             MIT
author:              ncaq
maintainer:          ncaq@ncaq.net
copyright:           © ncaq
category:            Text
ghc-options:         -Wall

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - text
  - utf8-string

library:
  source-dirs: src

tests:
  tasty:
    source-dirs: test
    main:        Main.hs
    dependencies:
      - string-transform
      - tasty
      - tasty-hunit
      - tasty-smallcheck
